[package]
name = "fork-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
env_logger = "0.8.4"
regex = "1.5.6"
lazy_static = "1.4.0"
serde_json = "1.0.81"
